env:
  contexts:
    - excludePaths: []
      name: baseline
      urls:
        - https://dev.drupal.qa.skpr.dev
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
  - type: passiveScan-config
    parameters:
      enableTags: false
      maxAlertsPerRule: 10
  - type: spider
    parameters:
      maxDuration: 1
      url: https://dev.drupal.qa.skpr.dev
  - type: passiveScan-wait
    parameters:
      maxDuration: 0
  - type: report
    parameters:
      reportDescription: ''
      reportFile: dast.sarif
      reportTitle: ZAP Scanning Report
      template: sarif-json