name: Deploy Stage

on:
  push:
    tags:
      - 'v*'

env:
  SKPR_USERNAME: ${{ vars.SKPR_QA_USERNAME }}
  SKPR_PASSWORD: ${{ secrets.SKPR_QA_PASSWORD }}

concurrency:
  group: deploy-stg
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️  Checkout Code
        uses: actions/checkout@v6

      - name: Setup skpr
        uses: skpr/setup-action@v1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get version
        id: version
        run: |
          version=${{ github.ref_name }}
          echo "::notice:: Using version $version from git tag"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 📦 Package
        run: skpr package ${{ steps.version.outputs.version }}

      - name: 🚀 Deploy
        run: skpr deploy stg ${{ steps.version.outputs.version }}

      - name: 🧹 Post-deploy
        run: skpr exec stg "drush updb -y"

