name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'
      timezone: 'Australia/Sydney'
  workflow_dispatch:

concurrency:
  group: security-scan
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v6

      - name: Setup skpr
        uses: skpr/setup-action@v1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 📦 Package
        run: skpr package sast --no-push

      - name: 🔍 Trivy scan (fpm)
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: localhost/skpr/drupal:sast-fpm
          format: sarif
          output: sast-fpm.sarif
          exit-code: "0"

      - name: ⬆️ Upload Trivy SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sast-fpm.sarif
          category: trvy-fpm

      - name: 🔍 Trivy scan (cli)
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: localhost/skpr/drupal:sast-cli
          format: sarif
          output: sast-cli.sarif
          exit-code: "0"

      - name: ⬆️ Upload Trivy SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sast-fpm.sarif
          category: trvy-cli

      - name: 🔍 Trivy scan (nginx)
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: localhost/skpr/drupal:sast-nginx
          format: sarif
          output: sast-nginx.sarif
          exit-code: "0"

      - name: ⬆️ Upload Trivy SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sast-nginx.sarif
          category: trvy-nginx
